import {Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {BarChart3,Globe2} from 'lucide-react';
import {money} from './utils';
import {Surface,Tabs,TabsContent,TabsList,TabsTrigger} from './ui';

export type AnalyticsDailyV59={day:string;revenue:number;orders:number};
export type AnalyticsSourceV59={name:string;source:string;sessions:number;views:number;checkouts:number;orders:number;revenue:number;conversion:number};
export type AnalyticsFunnelV59={name:string;value:number};
export type AnalyticsPaymentV59={name:string;value:number};

const palette=['#2f6848','#7f312e','#c69045','#789288','#4c6f91','#966b8f'];

export function AnalyticsChartsV59({daily,sourceData,funnel,payment}:{daily:AnalyticsDailyV59[];sourceData:AnalyticsSourceV59[];funnel:AnalyticsFunnelV59[];payment:AnalyticsPaymentV59[]}){
  return <Tabs defaultValue="revenue"><TabsList><TabsTrigger value="revenue">Doanh thu</TabsTrigger><TabsTrigger value="sources">Nguồn chuyển đổi</TabsTrigger><TabsTrigger value="funnel">Checkout funnel</TabsTrigger><TabsTrigger value="payments">Thanh toán</TabsTrigger></TabsList>
    <TabsContent value="revenue"><Surface className="v15-chart-card"><header><div><small>14 NGÀY GẦN NHẤT</small><h3>Doanh thu theo ngày</h3></div><BarChart3/></header><div className="v15-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={daily} margin={{top:12,right:12,left:0,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day"/><YAxis tickFormatter={value=>`${Math.round(Number(value)/1000000)}tr`}/><Tooltip formatter={value=>money(Number(value))}/><Line type="monotone" dataKey="revenue" stroke="#2f6848" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div></Surface></TabsContent>
    <TabsContent value="sources"><Surface className="v15-chart-card v16-source-card"><header><div><small>FIRST-TOUCH ATTRIBUTION</small><h3>Nguồn tạo phiên và đơn hàng</h3></div><Globe2/></header>{sourceData.length?<><div className="v15-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={sourceData} margin={{top:8,right:12,left:0,bottom:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip formatter={(value,name)=>name==='revenue'?money(Number(value)):String(value)}/><Legend/><Bar dataKey="sessions" name="Phiên" fill="#789288" radius={[6,6,0,0]}/><Bar dataKey="orders" name="Đơn hàng" fill="#2f6848" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div><div className="v16-source-table"><div className="head"><span>Nguồn</span><span>Phiên</span><span>Checkout</span><span>Đơn</span><span>Chuyển đổi</span><span>Doanh thu</span></div>{sourceData.map(item=><div key={item.source}><b>{item.name}</b><span>{item.sessions}</span><span>{item.checkouts}</span><span>{item.orders}</span><span>{item.conversion.toFixed(1)}%</span><strong>{money(item.revenue)}</strong></div>)}</div></>:<div className="v16-analytics-empty"><Globe2/><h4>Chưa có dữ liệu nguồn</h4><p>Website bắt đầu lưu UTM, referrer, campaign, thiết bị và first-touch session cho các lượt truy cập mới.</p></div>}</Surface></TabsContent>
    <TabsContent value="funnel"><Surface className="v15-chart-card"><header><div><small>STORE → CHECKOUT</small><h3>Phễu chuyển đổi</h3></div></header><div className="v15-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={funnel} layout="vertical" margin={{left:24,right:24}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number"/><YAxis dataKey="name" type="category" width={130}/><Tooltip/><Bar dataKey="value" radius={[0,8,8,0]}>{funnel.map((_,index)=><Cell key={index} fill={palette[index%palette.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></Surface></TabsContent>
    <TabsContent value="payments"><Surface className="v15-chart-card"><header><div><small>PAYMENT MIX</small><h3>Phương thức thanh toán</h3></div></header><div className="v15-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={payment}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Legend/><Bar dataKey="value" name="Số đơn" fill="#2f6848" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></Surface></TabsContent>
  </Tabs>;
}
