import {BadgePercent,Check,CreditCard,ExternalLink,Landmark,Link2,PackageCheck,Plus,Save,Settings2,ShieldCheck,Star,Trash2,Truck} from 'lucide-react';
import {useEffect,useState} from 'react';
import {buildTrackingUrl,defaultIntegrationSettings,loadIntegrationSettings,normalizeIntegrationSettings,saveIntegrationSettings} from './integrations';
import type {BankAccount,IntegrationSettings} from './types';
import {uid} from './utils';
import './v515-order-payment.css';

const emit=(message:string,tone:'success'|'danger'|'info'='success')=>window.dispatchEvent(new CustomEvent('timeforge:toast',{detail:{message,tone}}));
function Switch({checked,onChange}:{checked:boolean;onChange:(checked:boolean)=>void}){return <button type="button" className={`v13-switch ${checked?'on':''}`} aria-pressed={checked} onClick={()=>onChange(!checked)}><span/></button>}

export function IntegrationsV13(){
 const[settings,setSettings]=useState<IntegrationSettings>(defaultIntegrationSettings);
 const[loading,setLoading]=useState(true);const[dirty,setDirty]=useState(false);const[saving,setSaving]=useState(false);const[testTracking,setTestTracking]=useState('TF123456789');
 useEffect(()=>{void loadIntegrationSettings().then(value=>{setSettings(normalizeIntegrationSettings(value));setLoading(false)})},[]);
 const patch=<K extends keyof IntegrationSettings>(group:K,value:Partial<IntegrationSettings[K]>)=>{setSettings(current=>normalizeIntegrationSettings({...current,[group]:{...current[group],...value}}));setDirty(true)};
 const patchAccount=(id:string,value:Partial<BankAccount>)=>patch('payment',{bankAccounts:settings.payment.bankAccounts.map(item=>item.id===id?{...item,...value}:item)});
 const addAccount=()=>{const account:BankAccount={id:uid('bank'),bankName:'',accountName:'',accountNumber:'',branch:'',note:'',enabled:true,priority:settings.payment.bankAccounts.length+1};patch('payment',{bankAccounts:[...settings.payment.bankAccounts,account],preferredBankAccountId:settings.payment.preferredBankAccountId||account.id})};
 const removeAccount=(id:string)=>{const next=settings.payment.bankAccounts.filter(item=>item.id!==id);patch('payment',{bankAccounts:next,preferredBankAccountId:settings.payment.preferredBankAccountId===id?(next.find(item=>item.enabled)?.id||next[0]?.id||''):settings.payment.preferredBankAccountId})};
 const save=async()=>{setSaving(true);try{const normalized=await saveIntegrationSettings(settings);setSettings(normalized);setDirty(false);emit('Đã lưu cấu hình thanh toán, ngân hàng và giao hàng')}catch(reason){emit(reason instanceof Error?reason.message:'Không thể lưu cấu hình','danger')}finally{setSaving(false)}};
 if(loading)return <div className="v13-settings-loading"><span/><span/><span/></div>;
 return <div className="v13-integrations-page">
  {dirty&&<div className="v13-integration-savebar"><div><span/><b>Chưa lưu thay đổi</b></div><button onClick={()=>void loadIntegrationSettings().then(value=>{setSettings(value);setDirty(false)})}>Bỏ thay đổi</button><button className="primary" onClick={save} disabled={saving}><Save/>{saving?'Đang lưu...':'Lưu'}</button></div>}
  <div className="v13-admin-heading"><div><small>SETTINGS</small><h2>Thanh toán & giao hàng</h2><p>Cấu hình tài khoản nhận tiền, ưu đãi chuyển khoản, PayOS và vận chuyển.</p></div><button className="v13-primary" onClick={save} disabled={saving}><Save/>{saving?'Đang lưu...':'Lưu cấu hình'}</button></div>
  <div className="v13-integrations-grid"><main>
   <section className="v13-settings-card"><header><span><CreditCard/></span><div><h3>Phương thức thanh toán</h3><p>Chọn những lựa chọn được hiển thị tại checkout.</p></div></header>
    <div className="v13-setting-row"><div><b>Thanh toán khi nhận hàng</b><small>Khách thanh toán cho đơn vị vận chuyển khi nhận.</small></div><Switch checked={settings.payment.cod} onChange={checked=>patch('payment',{cod:checked})}/></div>
    <div className="v13-setting-row"><div><b>Chuyển khoản ngân hàng</b><small>Hiển thị tài khoản ưu tiên và chờ Admin xác nhận đã nhận tiền.</small></div><Switch checked={settings.payment.bankTransfer} onChange={checked=>patch('payment',{bankTransfer:checked})}/></div>
    <div className="v13-setting-row"><div><b>PayOS · QR ngân hàng</b><small>Khách quét QR trên trang PayOS; webhook tự xác nhận thanh toán.</small></div><Switch checked={settings.payment.online} onChange={checked=>patch('payment',{online:checked,onlineProvider:'payos'})}/></div>
    {settings.payment.online&&<div className="v13-settings-fields"><label><span>Provider</span><select value={settings.payment.onlineProvider} onChange={event=>patch('payment',{onlineProvider:event.target.value as 'generic'|'payos'})}><option value="payos">PayOS</option><option value="generic">Generic payment API</option></select></label><label className="full"><span>Payment create endpoint</span><input value={settings.payment.createEndpoint} onChange={event=>patch('payment',{createEndpoint:event.target.value})} placeholder="/api/payments/create"/></label><div className="v13-secure-note full"><ShieldCheck/><p><code>PAYOS_CLIENT_ID</code>, <code>PAYOS_API_KEY</code> và <code>PAYOS_CHECKSUM_KEY</code> chỉ đặt trên Vercel. Không lưu các secret này vào Firebase.</p></div></div>}
   </section>

   {settings.payment.bankTransfer&&<section className="v13-settings-card tf515-bank-admin"><header><span><Landmark/></span><div><h3>Thông tin tài khoản ngân hàng chuyển khoản</h3><p>Thêm nhiều ngân hàng và chọn một tài khoản ưu tiên để hiển thị cho khách.</p></div><button type="button" className="tf515-add-bank" onClick={addAccount}><Plus/>Thêm ngân hàng</button></header>
    <div className="tf515-bank-list">{settings.payment.bankAccounts.map((account,index)=><article className={`tf515-bank-card ${settings.payment.preferredBankAccountId===account.id?'is-preferred':''}`} key={account.id}>
      <div className="tf515-bank-card-head"><div><span>{index+1}</span><div><b>{account.bankName||'Ngân hàng mới'}</b><small>{account.accountNumber||'Chưa nhập số tài khoản'}</small></div></div><div><button type="button" className={settings.payment.preferredBankAccountId===account.id?'is-active':''} onClick={()=>patch('payment',{preferredBankAccountId:account.id})}><Star/>{settings.payment.preferredBankAccountId===account.id?'Đang ưu tiên':'Đặt ưu tiên'}</button><button type="button" className="danger" onClick={()=>removeAccount(account.id)} disabled={settings.payment.bankAccounts.length===1}><Trash2/></button></div></div>
      <div className="v13-settings-fields"><label><span>Tên ngân hàng</span><input value={account.bankName} onChange={event=>patchAccount(account.id,{bankName:event.target.value})} placeholder="Vietcombank"/></label><label><span>Số tài khoản</span><input value={account.accountNumber} onChange={event=>patchAccount(account.id,{accountNumber:event.target.value.replace(/\s/g,'')})} placeholder="0123456789" inputMode="numeric"/></label><label><span>Chủ tài khoản</span><input value={account.accountName} onChange={event=>patchAccount(account.id,{accountName:event.target.value.toUpperCase()})} placeholder="NGUYEN VAN A"/></label><label><span>Chi nhánh</span><input value={account.branch} onChange={event=>patchAccount(account.id,{branch:event.target.value})} placeholder="Không bắt buộc"/></label><label className="full"><span>Ghi chú</span><input value={account.note} onChange={event=>patchAccount(account.id,{note:event.target.value})} placeholder="Nội dung bổ sung cho khách"/></label></div>
      <div className="tf515-bank-card-footer"><span><b>Hiển thị tại checkout</b><small>Tắt để tạm ẩn tài khoản này.</small></span><Switch checked={account.enabled} onChange={checked=>patchAccount(account.id,{enabled:checked})}/></div>
    </article>)}</div>
    <div className="tf515-transfer-discount"><div className="tf515-transfer-discount-head"><span><BadgePercent/></span><div><b>Ưu đãi khi chuyển khoản trước</b><small>Giảm theo phần trăm hoặc số tiền cố định trên đơn hàng.</small></div><Switch checked={settings.payment.bankTransferDiscount.enabled} onChange={enabled=>patch('payment',{bankTransferDiscount:{...settings.payment.bankTransferDiscount,enabled}})}/></div>{settings.payment.bankTransferDiscount.enabled&&<div className="v13-settings-fields"><label><span>Kiểu giảm</span><select value={settings.payment.bankTransferDiscount.type} onChange={event=>patch('payment',{bankTransferDiscount:{...settings.payment.bankTransferDiscount,type:event.target.value as 'percentage'|'fixed_amount'}})}><option value="percentage">Phần trăm đơn hàng</option><option value="fixed_amount">Số tiền cố định</option></select></label><label><span>{settings.payment.bankTransferDiscount.type==='percentage'?'Mức giảm (%)':'Mức giảm (VND)'}</span><input type="number" min="0" max={settings.payment.bankTransferDiscount.type==='percentage'?100:undefined} value={settings.payment.bankTransferDiscount.value} onChange={event=>patch('payment',{bankTransferDiscount:{...settings.payment.bankTransferDiscount,value:Math.max(0,Number(event.target.value))}})}/></label><label className="full"><span>Đơn hàng tối thiểu</span><input type="number" min="0" value={settings.payment.bankTransferDiscount.minimumSubtotal} onChange={event=>patch('payment',{bankTransferDiscount:{...settings.payment.bankTransferDiscount,minimumSubtotal:Math.max(0,Number(event.target.value))}})}/></label></div>}</div>
   </section>}

   <section className="v13-settings-card"><header><span><Truck/></span><div><h3>Giao hàng & tracking</h3><p>Dùng template URL để mở trang theo dõi từ mã vận đơn.</p></div></header><div className="v13-settings-fields"><label><span>Đơn vị mặc định</span><select value={settings.shipping.defaultCarrier} onChange={event=>patch('shipping',{defaultCarrier:event.target.value})}><option>GHN</option><option>GHTK</option><option>Viettel Post</option><option>J&T Express</option><option>DHL</option><option>Khác</option></select></label><label><span>Ngưỡng miễn phí giao hàng</span><input type="number" min="0" value={settings.shipping.freeShippingThreshold} onChange={event=>patch('shipping',{freeShippingThreshold:Number(event.target.value)})}/></label><label className="full"><span>Tracking URL template</span><input value={settings.shipping.trackingUrlTemplate} onChange={event=>patch('shipping',{trackingUrlTemplate:event.target.value})} placeholder="https://carrier.com/track/{trackingNumber}"/></label><label className="full check"><input type="checkbox" checked={settings.shipping.insured} onChange={event=>patch('shipping',{insured:event.target.checked})}/><span>Bật mặc định giao hàng có bảo hiểm cho sản phẩm giá trị cao</span></label></div><div className="v13-tracking-test"><label><span>Mã vận đơn thử</span><input value={testTracking} onChange={event=>setTestTracking(event.target.value)}/></label><a href={buildTrackingUrl(settings.shipping.trackingUrlTemplate,testTracking)} target="_blank" rel="noreferrer"><ExternalLink/>Mở liên kết thử</a></div></section>
   <section className="v13-settings-card"><header><span><Settings2/></span><div><h3>Customer Account</h3><p>Cấu hình thời hạn và bước xác minh tài khoản khách.</p></div></header><div className="v13-settings-fields"><label><span>Thời hạn phiên (phút)</span><input type="number" min="5" max="1440" value={settings.customerAccount.sessionMinutes} onChange={event=>patch('customerAccount',{sessionMinutes:Math.max(5,Number(event.target.value))})}/></label><label className="check"><input type="checkbox" checked={settings.customerAccount.requireOrderChallenge} onChange={event=>patch('customerAccount',{requireOrderChallenge:event.target.checked})}/><span>Yêu cầu xác minh mã đơn gần nhất</span></label></div></section>
  </main><aside><section className="v13-adapter-card"><small>ORDER FLOW</small><h3>Luồng đơn hàng production</h3><ol><li><span>1</span>Checkout gửi giỏ hàng và thông tin giao hàng đến API.</li><li><span>2</span>Server đọc giá, tồn kho và ưu đãi từ Firebase.</li><li><span>3</span>Đơn, khách hàng và tồn kho được ghi đồng bộ.</li><li><span>4</span>Admin nhận đơn mới theo thời gian thực.</li><li><span>5</span>PayOS dùng webhook; chuyển khoản thường do Admin xác nhận.</li></ol></section><section className="v13-adapter-card accent"><PackageCheck/><h3>Đã chuẩn bị</h3><ul><li><Check/>Tạo đơn qua server</li><li><Check/>Nhiều tài khoản ngân hàng</li><li><Check/>Ưu đãi chuyển khoản</li><li><Check/>PayOS webhook xác minh</li><li><Check/>Vận chuyển và tracking</li></ul></section><section className="v13-adapter-card"><Link2/><h3>Environment Variables</h3><code>FIREBASE_DATABASE_URL</code><code>FIREBASE_DATABASE_AUTH</code><code>PAYOS_CLIENT_ID</code><code>PAYOS_API_KEY</code><code>PAYOS_CHECKSUM_KEY</code><code>PUBLIC_SITE_URL</code></section></aside></div>
 </div>;
}
