import './referral-v68.css';
import './referral-ops-link-v681.css';
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,Copy,ExternalLink,Gift,Link2,RefreshCw,ShieldCheck,Users} from 'lucide-react';
import {toast} from 'sonner';
import {useCommerce} from './context';
import {Button} from './ui';
import {defaultReferralSettings,loadReferralSettings,referralCodeForCustomer,referralLinkForCustomer,saveReferralSettings,type ReferralSettings} from './referral-v68';
import {money} from './utils';

const Toggle=({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description:string})=><label className="rf68-toggle-row"><span><b>{label}</b><small>{description}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i/></label>;
export function ReferralAdminV68(){
 const{customers,orders,updateOrder}=useCommerce();const[settings,setSettings]=useState<ReferralSettings>(defaultReferralSettings);const[saving,setSaving]=useState(false);const[search,setSearch]=useState('');
 useEffect(()=>{void loadReferralSettings().then(setSettings)},[]);
 const referralOrders=useMemo(()=>orders.filter(order=>Boolean(order.referralCode)),[orders]);
 const paid=referralOrders.filter(o=>o.paymentStatus==='paid'||o.status==='completed');const referredRevenue=paid.reduce((s,o)=>s+o.total,0);const pending=referralOrders.filter(o=>o.referralRewardStatus==='pending'||o.referralRewardStatus==='review').length;const blocked=referralOrders.filter(o=>o.referralRewardStatus==='blocked').length;
 const filtered=customers.filter(c=>`${c.name} ${c.email} ${c.phone}`.toLowerCase().includes(search.toLowerCase())).slice(0,12);
 const save=async()=>{setSaving(true);try{await saveReferralSettings(settings);toast.success('Đã lưu chính sách referral');}catch(e){toast.error(e instanceof Error?e.message:'Không thể lưu cấu hình')}finally{setSaving(false)}};
 const copy=async(text:string)=>{await navigator.clipboard?.writeText(text);toast.success('Đã sao chép link giới thiệu')};
 return <div className="rf68-admin">
  <section className="rf68-kpis"><article><span><Users/></span><div><small>Đơn referral</small><b>{referralOrders.length}</b></div></article><article><span><Gift/></span><div><small>Doanh thu qualified/paid</small><b>{money(referredRevenue)}</b></div></article><article><span><RefreshCw/></span><div><small>Chờ kiểm tra</small><b>{pending}</b></div></article><article><span><ShieldCheck/></span><div><small>Bị chặn</small><b>{blocked}</b></div></article></section>
  <section className="rf68-ops-entry"><div><RefreshCw/><span><b>Operations & Release Center</b><p>Triage exception theo business impact, chạy UAT, quản lý release blocker/rollback và theo dõi As-is → To-be.</p></span></div><a href="/admin/product-ops">Mở Product Ops</a></section>
  <div className="rf68-grid"><section className="rf68-card"><header><div><small>GROWTH CONFIG</small><h2>Chính sách giới thiệu</h2><p>Admin có thể đổi giữa giảm theo % hoặc số tiền cố định mà không sửa code.</p></div><label className="rf68-master"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/><span>{settings.enabled?'Đang bật':'Đang tắt'}</span></label></header>
   <div className="rf68-form-grid"><label><span>Ưu đãi người được giới thiệu</span><select value={settings.friendRewardType} onChange={e=>setSettings({...settings,friendRewardType:e.target.value as ReferralSettings['friendRewardType']})}><option value="percentage">Phần trăm (%)</option><option value="fixed_amount">Số tiền cố định (₫)</option></select></label><label><span>Giá trị ưu đãi</span><input type="number" min="0" value={settings.friendRewardValue} onChange={e=>setSettings({...settings,friendRewardValue:Number(e.target.value)})}/></label><label><span>Thưởng người giới thiệu</span><select value={settings.referrerRewardType} onChange={e=>setSettings({...settings,referrerRewardType:e.target.value as ReferralSettings['referrerRewardType']})}><option value="percentage">Phần trăm (%)</option><option value="fixed_amount">Số tiền cố định (₫)</option></select></label><label><span>Giá trị thưởng</span><input type="number" min="0" value={settings.referrerRewardValue} onChange={e=>setSettings({...settings,referrerRewardValue:Number(e.target.value)})}/></label><label><span>Đơn tối thiểu</span><input type="number" min="0" value={settings.minimumSubtotal} onChange={e=>setSettings({...settings,minimumSubtotal:Number(e.target.value)})}/></label><label><span>Chờ sau giao hàng (ngày)</span><input type="number" min="0" value={settings.rewardDelayDays} onChange={e=>setSettings({...settings,rewardDelayDays:Number(e.target.value)})}/></label></div>
   <div className="rf68-actions"><Button onClick={()=>void save()} disabled={saving}>{saving?'Đang lưu…':'Lưu chính sách'}</Button></div>
  </section>
  <section className="rf68-card"><header><div><small>FRAUD RULE ENGINE</small><h2>Chống gian lận</h2><p>Tín hiệu rủi ro chỉ hỗ trợ quyết định; reward chỉ phát sau khi đơn đủ điều kiện.</p></div><ShieldCheck/></header>
   <div className="rf68-toggles"><Toggle checked={settings.requireFirstOrder} onChange={v=>setSettings({...settings,requireFirstOrder:v})} label="Chỉ áp dụng khách mua lần đầu" description="Khách đã có đơn trước đó sẽ không được tính là referral mới."/><Toggle checked={settings.useEmailAntiFraud} onChange={v=>setSettings({...settings,useEmailAntiFraud:v,requireVerifiedEmail:v?settings.requireVerifiedEmail:false})} label="Dùng email làm tiêu chí chống gian lận" description="Tắt tùy chọn này để email không ảnh hưởng Fraud Score hoặc eligibility."/>{settings.useEmailAntiFraud&&<Toggle checked={settings.requireVerifiedEmail} onChange={v=>setSettings({...settings,requireVerifiedEmail:v})} label="Yêu cầu email đã xác thực" description="Có thể nối với OTP email miễn phí; nếu chưa cấu hình delivery thì vẫn giữ ở trạng thái review."/>}</div>
   <div className="rf68-form-grid compact"><label><span>Trùng IP</span><select value={settings.sameIpMode} onChange={e=>setSettings({...settings,sameIpMode:e.target.value as ReferralSettings['sameIpMode']})}><option value="allow">Cho phép</option><option value="review">Đưa vào review</option><option value="block">Chặn</option></select></label><label><span>Trùng thiết bị</span><select value={settings.sameDeviceMode} onChange={e=>setSettings({...settings,sameDeviceMode:e.target.value as ReferralSettings['sameDeviceMode']})}><option value="allow">Cho phép</option><option value="review">Đưa vào review</option><option value="block">Chặn</option></select></label><label><span>Trùng địa chỉ</span><select value={settings.sameAddressMode} onChange={e=>setSettings({...settings,sameAddressMode:e.target.value as ReferralSettings['sameAddressMode']})}><option value="allow">Cho phép</option><option value="review">Đưa vào review</option><option value="block">Chặn</option></select></label><label><span>Giới hạn/ngày/người giới thiệu</span><input type="number" min="1" value={settings.maxReferralsPerDay} onChange={e=>setSettings({...settings,maxReferralsPerDay:Number(e.target.value)})}/></label></div>
  </section></div>
  <section className="rf68-card rf68-links"><header><div><small>REFERRAL LINKS</small><h2>Link giới thiệu khách hàng</h2><p>Link ổn định theo Customer ID, không cần tạo thủ công từng mã.</p></div><label className="rf68-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên, email, SĐT…"/></label></header>
   <div className="rf68-link-list">{filtered.map(c=>{const link=referralLinkForCustomer(c.id);return <article key={c.id}><span className="rf68-avatar">{c.name.slice(0,1).toUpperCase()}</span><div><b>{c.name}</b><small>{c.phone||c.email}</small></div><code>{referralCodeForCustomer(c.id)}</code><div className="rf68-row-actions"><button onClick={()=>void copy(link)} title="Sao chép"><Copy/></button><a href={link} target="_blank" rel="noreferrer" title="Mở link"><ExternalLink/></a></div></article>})}</div>
  </section>
  <section className="rf68-card rf68-queue"><header><div><small>GROWTH OPS QUEUE</small><h2>Referral review & qualification</h2><p>Hàng đợi giúp Ops xử lý exception thay vì sửa dữ liệu trực tiếp. Low-risk có thể theo dõi đến giao hàng; medium/high-risk cần review.</p></div></header><div className="rf68-table-wrap"><table><thead><tr><th>Đơn</th><th>Khách</th><th>Referral</th><th>Fraud score</th><th>Trạng thái</th><th></th></tr></thead><tbody>{referralOrders.slice(0,12).map(order=><tr key={order.id}><td><b>{order.number}</b><small>{new Date(order.createdAt).toLocaleDateString('vi-VN')}</small></td><td><b>{order.customerName}</b><small>{order.customerPhone}</small></td><td><code>{order.referralCode}</code><small>−{money(order.referralDiscountAmount||0)}</small></td><td><span className={`rf68-risk is-${order.referralRiskLevel||'low'}`}>{order.referralFraudScore||0} · {order.referralRiskLevel||'low'}</span><small>{order.referralRiskSignals?.[0]||'Không có tín hiệu mạnh'}</small></td><td><span className={`rf68-status is-${order.referralRewardStatus||'pending'}`}>{order.referralRewardStatus||'pending'}</span></td><td><div className="rf68-queue-actions"><button onClick={()=>{updateOrder(order.id,{referralRewardStatus:'qualified',referralQualifiedAt:new Date().toISOString()});toast.success('Đã đánh dấu qualified')}}><CheckCircle2/>Duyệt</button><button onClick={()=>{updateOrder(order.id,{referralRewardStatus:'revoked'});toast.info('Đã revoke reward')}}><AlertTriangle/>Revoke</button></div></td></tr>)}{!referralOrders.length&&<tr><td colSpan={6}><div className="rf68-empty"><Link2/><b>Chưa có referral order</b><span>Mở một referral link và tạo đơn thử để kiểm tra end-to-end flow.</span></div></td></tr>}</tbody></table></div></section>
  <section className="rf68-note"><AlertTriangle/><div><b>Nguyên tắc an toàn</b><p>Không block chỉ vì cùng IP. Hệ thống kết hợp lịch sử mua, device, IP hash, địa chỉ và email (nếu Admin bật) để tính Fraud Score. Reward của người giới thiệu ở trạng thái pending/review cho tới khi đơn được giao và qua thời gian chờ.</p></div></section>
 </div>
}