import {useEffect,useMemo} from 'react';
import {useLocation} from 'react-router-dom';
import {useStorefrontData,useStoreReviews} from './context';
import {useBlogPostsV18} from './blog-data-v18';
import {resolveStoreName} from './store-profile';
import {getSeoLandingByPath,matchSeoLandingProduct} from './seo-discovery-v657';
import {HOME_SEO_FAQS} from './seo-home-v658';
import {resolvesCollectionProducts} from './collection-utils';
import type {Product} from './types';

const FALLBACK_SITE='https://luxurytimeforge.vercel.app';
const FALLBACK_IMAGE='/social-cover.jpg';
const clean=(value:string)=>value.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const clamp=(value:string,max:number)=>value.length<=max?value:`${value.slice(0,Math.max(0,max-1)).trim()}…`;
const setMeta=(selector:string,attrs:Record<string,string>)=>{let node=document.head.querySelector<HTMLMetaElement>(selector);if(!node){node=document.createElement('meta');document.head.appendChild(node)}Object.entries(attrs).forEach(([key,value])=>node!.setAttribute(key,value))};
const setLink=(rel:string,href:string,type?:string)=>{let node=document.head.querySelector<HTMLLinkElement>(`link[rel="${rel}"]${type?`[type="${type}"]`:''}`);if(!node){node=document.createElement('link');node.rel=rel;if(type)node.type=type;document.head.appendChild(node)}node.href=href};
const gtinField=(barcode:string)=>{const digits=String(barcode||'').replace(/\D/g,'');return[8,12,13,14].includes(digits.length)?{[`gtin${digits.length}`]:digits}:{}};
const pageSeo:Record<string,{title:string;description:string}>={
  '/pages/about':{title:'Giới thiệu Luxury TimeForge',description:'Tìm hiểu câu chuyện, tiêu chuẩn tuyển chọn sản phẩm và trải nghiệm mua đồng hồ tại Luxury TimeForge.'},
  '/pages/warranty':{title:'Chính sách bảo hành đồng hồ',description:'Chính sách bảo hành đồng hồ tại Luxury TimeForge: thời hạn, quy trình tiếp nhận và các trường hợp hỗ trợ.'},
  '/pages/shipping':{title:'Chính sách giao hàng đồng hồ',description:'Thông tin giao hàng, thời gian dự kiến, đóng gói và hỗ trợ theo dõi đơn hàng từ Luxury TimeForge.'},
  '/pages/returns':{title:'Chính sách đổi trả đồng hồ',description:'Điều kiện và quy trình đổi trả sản phẩm tại Luxury TimeForge.'},
};
const toPostalAddress=(value:string)=>value?{'@type':'PostalAddress',streetAddress:value,addressCountry:'VN'}:undefined;
const productAttributeLabels:Record<string,string>={gender:'Giới tính',faceshape:'Hình dạng mặt số',face_shape:'Hình dạng mặt số',dial_shape:'Hình dạng mặt số',watch_face_shape:'Hình dạng mặt số',facesize:'Kích thước mặt số',face_size:'Kích thước mặt số',case_size:'Kích thước mặt số',diameter:'Kích thước mặt số',duong_kinh:'Kích thước mặt số',bandmaterial:'Chất liệu dây',band_material:'Chất liệu dây',strap_material:'Chất liệu dây',watch_band_material:'Chất liệu dây',bandcolor:'Màu dây',band_color:'Màu dây',strap_color:'Màu dây',casecolor:'Màu vỏ',case_color:'Màu vỏ',watch_case_color:'Màu vỏ',classification:'Phân loại',watch_type:'Phân loại',movement:'Bộ máy',phan_loai:'Phân loại'};
const normalizeAttributeKey=(value:string)=>value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLocaleLowerCase('vi-VN').replace(/[\s.-]+/g,'_');
const productAdditionalProperties=(product:Product)=>{const seen=new Set<string>();return(product.metafields||[]).flatMap(field=>{const name=productAttributeLabels[normalizeAttributeKey(field.key||'')],value=String(field.value||'').trim();if(!name||!value||seen.has(name))return[];seen.add(name);return[{'@type':'PropertyValue',name,value}]})};

export function SeoHeadV60(){
  const location=useLocation();
  const{products,collections,productGroups,storeProfile,isLoading}=useStorefrontData();
  const reviews=useStoreReviews();
  const{posts}=useBlogPostsV18();
  const seo=useMemo(()=>{
    let site=(String(import.meta.env.VITE_PUBLIC_SITE_URL||'').trim()||FALLBACK_SITE).replace(/\/$/,'');
    if(/localhost|127\.0\.0\.1/i.test(site)&&import.meta.env.PROD)site=FALLBACK_SITE;
    const storeName=resolveStoreName(storeProfile.storeName),path=location.pathname;
    const searchParams=new URLSearchParams(location.search);const pageParam=Number(searchParams.get('page')||'1');const page=Number.isInteger(pageParam)&&pageParam>1?pageParam:1;
    const productHandle=path.startsWith('/products/')?decodeURIComponent(path.slice('/products/'.length)):'';
    const product=productHandle?products.find(item=>item.handle===productHandle):undefined;
    const collectionHandle=path.startsWith('/collections/')?decodeURIComponent(path.slice('/collections/'.length)):'';
    const collection=collectionHandle?collections.find(item=>item.handle===collectionHandle):undefined;
    const postHandle=path.startsWith('/blogs/')?decodeURIComponent(path.slice('/blogs/'.length)):'';
    const post=postHandle?posts.find(item=>item.handle===postHandle&&item.status==='published'):undefined;
    const landing=getSeoLandingByPath(path);
    const landingProducts=landing?products.filter(item=>matchSeoLandingProduct(landing,item)):[];
    const collectionProducts=collection?resolvesCollectionProducts(collection,products).filter(item=>item.status==='active'&&item.published!==false):[];
    let title=storeProfile.seoTitle||`${storeName} | Đồng hồ chính hãng`,description=storeProfile.seoDescription||storeProfile.storeDescription||'Đồng hồ chính hãng, thông tin minh bạch, giao hàng toàn quốc và hỗ trợ hậu mãi từ Luxury TimeForge.',image=storeProfile.socialShareImage||storeProfile.logoImage||FALLBACK_IMAGE,type='website',noindex=false;
    if(product){title=product.seoTitle||`${product.title} chính hãng | ${storeName}`;description=product.seoDescription||product.descriptionText||clean(product.descriptionHtml)||`${product.title} chính hãng tại ${storeName}. Xem giá, tình trạng hàng, thông số và chính sách bảo hành.`;image=product.images[0]||image;type='product'}
    else if(landing){title=`${landing.title} | ${storeName}`;description=landing.description;image=landingProducts[0]?.images[0]||image}
    else if(collection){title=`${collection.title} | Đồng hồ chính hãng | ${storeName}`;description=collection.description||`Khám phá bộ sưu tập ${collection.title} được ${storeName} tuyển chọn.`;image=collection.image||image}
    else if(path==='/collections'){title=`Đồng hồ chính hãng | ${storeName}`;description='Khám phá đồng hồ theo thương hiệu, mức giá, giới tính, chất liệu dây, kích thước mặt và tình trạng còn hàng.'}
    else if(path==='/watch-finder'){title=`Tư vấn chọn đồng hồ theo nhu cầu | ${storeName}`;description='Tìm mẫu đồng hồ phù hợp theo phong cách, kích thước và ngân sách với công cụ tư vấn của Luxury TimeForge.'}
    else if(path==='/blogs'){title=`Kiến thức & tư vấn đồng hồ | TimeForge Journal`;description='Kiến thức, cảm hứng, hướng dẫn chọn và chăm sóc đồng hồ từ Luxury TimeForge.'}
    else if(post){title=`${post.title} | TimeForge Journal`;description=post.excerpt||clean(post.contentHtml)||'Bài viết và góc nhìn về đồng hồ từ Luxury TimeForge.';image=post.image||image;type='article'}
    else if(path.startsWith('/blogs/')){title=`TimeForge Journal | ${storeName}`;description='Bài viết và góc nhìn về đồng hồ từ Luxury TimeForge.'}
    else if(pageSeo[path]){title=`${pageSeo[path].title} | ${storeName}`;description=pageSeo[path].description}
    else if(path.startsWith('/pages/')){const slug=path.split('/').filter(Boolean).pop()||'';title=`${slug.replace(/-/g,' ')} | ${storeName}`}
    else if(path==='/search'||path==='/wishlist'||path==='/compare'||path==='/cart'||path==='/checkout'||path==='/404'||path==='/track-order'||path.startsWith('/account')||path.startsWith('/order-confirmation')||path.startsWith('/payment/')||path.startsWith('/admin'))noindex=true;
    const canonicalPath=path==='/'?'':path.replace(/\/$/,'');const paginatedRoute=path==='/collections'||path.startsWith('/collections/')||path==='/blogs';const canonicalSearch=paginatedRoute&&page>1?`?page=${page}`:'';if(canonicalSearch)title=`${title} – Trang ${page}`;const canonical=`${site}${canonicalPath}${canonicalSearch}`;const absoluteImage=/^https?:\/\//i.test(image)?image:`${site}${image.startsWith('/')?'':'/'}${image}`;
    const dynamicDataRoute=Boolean(landing||productHandle||collectionHandle||postHandle);const deferHeadUpdate=isLoading&&dynamicDataRoute;
    return{site,storeName,path,title:clamp(clean(title),68),description:clamp(clean(description),158),image:absoluteImage,type,noindex,canonical,product,collection,collectionProducts,landing,landingProducts,post,deferHeadUpdate};
  },[collections,isLoading,location.pathname,location.search,posts,products,storeProfile]);

  useEffect(()=>{
    if(seo.deferHeadUpdate)return;
    document.documentElement.lang='vi';document.title=seo.title;
    setMeta('meta[name="description"]',{name:'description',content:seo.description});
    setMeta('meta[name="robots"]',{name:'robots',content:seo.noindex?'noindex, nofollow':'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1'});
    const verification=String(import.meta.env.VITE_GOOGLE_SITE_VERIFICATION||'').trim();if(verification)setMeta('meta[name="google-site-verification"]',{name:'google-site-verification',content:verification});
    setMeta('meta[property="og:title"]',{property:'og:title',content:seo.title});setMeta('meta[property="og:description"]',{property:'og:description',content:seo.description});setMeta('meta[property="og:type"]',{property:'og:type',content:seo.type});setMeta('meta[property="og:url"]',{property:'og:url',content:seo.canonical});setMeta('meta[property="og:image"]',{property:'og:image',content:seo.image});setMeta('meta[property="og:image:secure_url"]',{property:'og:image:secure_url',content:seo.image});setMeta('meta[property="og:image:alt"]',{property:'og:image:alt',content:`${seo.storeName} — đồng hồ chính hãng`});setMeta('meta[property="og:locale"]',{property:'og:locale',content:'vi_VN'});setMeta('meta[property="og:site_name"]',{property:'og:site_name',content:seo.storeName});
    setMeta('meta[name="twitter:card"]',{name:'twitter:card',content:'summary_large_image'});setMeta('meta[name="twitter:title"]',{name:'twitter:title',content:seo.title});setMeta('meta[name="twitter:description"]',{name:'twitter:description',content:seo.description});setMeta('meta[name="twitter:image"]',{name:'twitter:image',content:seo.image});setLink('canonical',seo.canonical);setLink('alternate','/llms.txt','text/plain');setLink('alternate','/ai-catalog.json','application/json');
    const id='tf60-structured-data';let script=document.getElementById(id) as HTMLScriptElement|null;if(!script){script=document.createElement('script');script.id=id;script.type='application/ld+json';document.head.appendChild(script)}
    const logo=/^https?:\/\//i.test(storeProfile.logoImage)?storeProfile.logoImage:`${seo.site}${storeProfile.logoImage||'/luxury-timeforge-logo.svg'}`;
    const sameAs=[storeProfile.facebookUrl,storeProfile.instagramUrl,storeProfile.tiktokUrl].filter(value=>/^https?:\/\//i.test(String(value||'')));
    const organization={'@type':['OnlineStore','Organization'],'@id':`${seo.site}/#organization`,name:seo.storeName,alternateName:'Luxury TimeForge Vietnam',url:`${seo.site}/`,logo,image:seo.image,description:storeProfile.storeDescription||undefined,email:storeProfile.storeEmail||undefined,telephone:storeProfile.storePhone||undefined,address:toPostalAddress(storeProfile.storeAddress),areaServed:{'@type':'Country',name:'Vietnam'},currenciesAccepted:'VND',sameAs:sameAs.length?sameAs:undefined,contactPoint:(storeProfile.storePhone||storeProfile.storeEmail)?{'@type':'ContactPoint',telephone:storeProfile.storePhone||undefined,email:storeProfile.storeEmail||undefined,contactType:'customer service',areaServed:'VN',availableLanguage:['vi']}:undefined,hasMerchantReturnPolicy:{'@type':'MerchantReturnPolicy',merchantReturnLink:`${seo.site}/pages/returns`,applicableCountry:'VN'},hasShippingService:{'@type':'ShippingService','@id':`${seo.site}/#standard-shipping`,name:'Giao hàng tiêu chuẩn Luxury TimeForge',fulfillmentType:'https://schema.org/FulfillmentTypeDelivery',shippingConditions:{'@type':'ShippingConditions',shippingDestination:{'@type':'DefinedRegion',addressCountry:'VN'},transitTime:{'@type':'ServicePeriod',duration:{'@type':'QuantitativeValue',minValue:1,maxValue:4,unitCode:'DAY'}}}}};
    const website={'@type':'WebSite','@id':`${seo.site}/#website`,url:`${seo.site}/`,name:seo.storeName,alternateName:'Luxury TimeForge Vietnam',inLanguage:'vi-VN',publisher:{'@id':`${seo.site}/#organization`}};
    const crumbs=[{name:'Trang chủ',url:`${seo.site}/`}];if(seo.path!=='/'){if(seo.product)crumbs.push({name:'Đồng hồ',url:`${seo.site}/collections`});crumbs.push({name:seo.product?.title||seo.collection?.title||seo.landing?.title||seo.post?.title||pageSeo[seo.path]?.title||seo.title,url:seo.canonical})}
    const breadcrumb={'@type':'BreadcrumbList','@id':`${seo.canonical}#breadcrumb`,itemListElement:crumbs.map((item,index)=>({'@type':'ListItem',position:index+1,name:item.name,item:item.url}))};
    const productReviews=seo.product?reviews.filter(item=>item.status==='published'&&item.reviewType==='product'&&item.productId===seo.product?.id&&item.customerName.trim()):[];
    const productGroup=seo.product?productGroups.find(group=>group.status==='active'&&(group.items||[]).some(item=>item.productId===seo.product?.id||String(item.sku||'').toUpperCase()===String(seo.product?.sku||'').toUpperCase())):undefined;
    const averageRating=productReviews.length?productReviews.reduce((sum,item)=>sum+Math.min(5,Math.max(1,Number(item.rating)||5)),0)/productReviews.length:0;
    const productGroupId=productGroup?.id||productGroup?.skuPrefix||undefined;
    const currentGroupItem=seo.product&&productGroup?(productGroup.items||[]).find(item=>item.productId===seo.product?.id||String(item.sku||'').toUpperCase()===String(seo.product?.sku||'').toUpperCase()):undefined;
    const shippingDetails={'@type':'OfferShippingDetails',shippingDestination:{'@type':'DefinedRegion',addressCountry:'VN'},deliveryTime:{'@type':'ShippingDeliveryTime',transitTime:{'@type':'QuantitativeValue',minValue:1,maxValue:4,unitCode:'DAY'}}};
    const pageEntity=seo.product?{'@type':'Product','@id':`${seo.canonical}#product`,name:seo.product.title,url:seo.canonical,image:seo.product.images.filter(Boolean),description:seo.description,sku:seo.product.sku,mpn:seo.product.sku||undefined,category:seo.product.category||seo.product.productType||undefined,additionalProperty:productAdditionalProperties(seo.product).length?productAdditionalProperties(seo.product):undefined,inProductGroupWithID:productGroupId,isVariantOf:productGroupId?{'@id':`${seo.site}/#product-group-${encodeURIComponent(productGroupId)}`}:undefined,color:currentGroupItem?.color||undefined,size:currentGroupItem?.size||undefined,...gtinField(seo.product.barcode),brand:{'@type':'Brand',name:seo.product.vendor||seo.storeName},aggregateRating:productReviews.length?{'@type':'AggregateRating',ratingValue:Number(averageRating.toFixed(2)),reviewCount:productReviews.length,bestRating:5,worstRating:1}:undefined,review:productReviews.length?productReviews.slice(0,6).map(item=>({'@type':'Review',name:item.title||undefined,reviewBody:item.text||undefined,datePublished:item.createdAt?.slice(0,10)||undefined,reviewRating:{'@type':'Rating',ratingValue:item.rating,bestRating:5,worstRating:1},author:{'@type':'Person',name:item.customerName}})):undefined,offers:{'@type':'Offer',url:seo.canonical,priceCurrency:'VND',price:seo.product.price,availability:seo.product.inventory>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',itemCondition:'https://schema.org/NewCondition',seller:{'@id':`${seo.site}/#organization`},shippingDetails}}:seo.landing?{'@type':'CollectionPage','@id':`${seo.canonical}#webpage`,url:seo.canonical,name:seo.title,description:seo.description,inLanguage:'vi-VN',isPartOf:{'@id':`${seo.site}/#website`},breadcrumb:{'@id':`${seo.canonical}#breadcrumb`},mainEntity:{'@type':'ItemList',numberOfItems:seo.landingProducts.length,itemListElement:seo.landingProducts.slice(0,24).map((item,index)=>({'@type':'ListItem',position:index+1,url:`${seo.site}/products/${encodeURIComponent(item.handle)}`,name:item.title}))}}:seo.collection?{'@type':'CollectionPage','@id':`${seo.canonical}#webpage`,url:seo.canonical,name:seo.title,description:seo.description,inLanguage:'vi-VN',isPartOf:{'@id':`${seo.site}/#website`},breadcrumb:{'@id':`${seo.canonical}#breadcrumb`},mainEntity:seo.collectionProducts.length?{'@type':'ItemList',numberOfItems:seo.collectionProducts.length,itemListElement:seo.collectionProducts.slice(0,24).map((item,index)=>({'@type':'ListItem',position:index+1,url:`${seo.site}/products/${encodeURIComponent(item.handle)}`,name:item.title}))}:undefined}:{'@type':'WebPage','@id':`${seo.canonical}#webpage`,url:seo.canonical,name:seo.title,description:seo.description,inLanguage:'vi-VN',isPartOf:{'@id':`${seo.site}/#website`},breadcrumb:{'@id':`${seo.canonical}#breadcrumb`}};
    const articleEntity=seo.post?{'@type':'BlogPosting','@id':`${seo.canonical}#article`,headline:seo.post.title,description:seo.description,image:seo.image,datePublished:seo.post.publishedAt||undefined,dateModified:seo.post.updatedAt||seo.post.publishedAt||undefined,author:{'@type':'Organization',name:seo.post.author||seo.storeName,url:`${seo.site}/`},publisher:{'@id':`${seo.site}/#organization`},mainEntityOfPage:{'@id':`${seo.canonical}#webpage`},inLanguage:'vi-VN'}:undefined;
    const productGroupEntity=seo.product&&productGroup&&productGroupId?(()=>{const groupProducts=(productGroup.items||[]).map(item=>({item,product:products.find(candidate=>candidate.id===item.productId||String(candidate.sku||'').toUpperCase()===String(item.sku||'').toUpperCase())})).filter(entry=>entry.product?.published!==false&&entry.product?.status==='active'&&entry.product?.handle);const variesBy=[groupProducts.some(entry=>String(entry.item.color||'').trim())?'https://schema.org/color':'',groupProducts.some(entry=>String(entry.item.size||'').trim())?'https://schema.org/size':''].filter(Boolean);return{'@type':'ProductGroup','@id':`${seo.site}/#product-group-${encodeURIComponent(productGroupId)}`,productGroupID:productGroupId,name:productGroup.name||seo.product.title,description:productGroup.description||undefined,brand:{'@type':'Brand',name:productGroup.vendor||seo.product.vendor||seo.storeName},variesBy:variesBy.length?variesBy:undefined,hasVariant:groupProducts.map(({item,product})=>{const variant=product!;const url=`${seo.site}/products/${encodeURIComponent(variant.handle)}`;if(variant.id===seo.product?.id)return{'@id':`${seo.canonical}#product`};return{'@type':'Product','@id':`${url}#product`,name:variant.title,url,image:variant.images.filter(Boolean),sku:variant.sku,mpn:variant.sku||undefined,color:item.color||undefined,size:item.size||undefined,...gtinField(variant.barcode),offers:{'@type':'Offer',url,priceCurrency:'VND',price:variant.price,availability:variant.inventory>0?'https://schema.org/InStock':'https://schema.org/OutOfStock',itemCondition:'https://schema.org/NewCondition',seller:{'@id':`${seo.site}/#organization`},shippingDetails}}})}})():undefined;
    const faqEntity=seo.path==='/'?{'@type':'FAQPage','@id':`${seo.site}/#faq`,mainEntity:HOME_SEO_FAQS.map(item=>({'@type':'Question',name:item.question,acceptedAnswer:{'@type':'Answer',text:item.answer}}))}:undefined;
    script.textContent=JSON.stringify({'@context':'https://schema.org','@graph':[organization,website,breadcrumb,pageEntity,...(articleEntity?[articleEntity]:[]),...(productGroupEntity?[productGroupEntity]:[]),...(faqEntity?[faqEntity]:[])]});
  },[productGroups,products,reviews,seo,storeProfile.facebookUrl,storeProfile.instagramUrl,storeProfile.logoImage,storeProfile.storeAddress,storeProfile.storeDescription,storeProfile.storeEmail,storeProfile.storePhone,storeProfile.tiktokUrl]);
  return null;
}
