import{useMemo,useState}from'react';
import{ShieldCheck,UserPlus,UsersRound,Check,LockKeyhole}from'lucide-react';
import{roleLabels,rolePermissions,type AdminRole}from'./permissions';
import{useAuth}from'./auth';
import{Button}from'./ui';

type Member={id:string;email:string;name:string;role:AdminRole;status:'active'|'invited'};
const key='tf.v20.team';
const read=():Member[]=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
export function TeamPermissionsV20(){const{user}=useAuth();const[members,setMembers]=useState<Member[]>(()=>{const saved=read();return saved.length?saved:[{id:'owner',email:user?.email||'owner@timeforge.local',name:user?.name||'Chủ cửa hàng',role:'owner',status:'active'}]});const[email,setEmail]=useState('');const[name,setName]=useState('');const[role,setRole]=useState<AdminRole>('staff');
 const save=(next:Member[])=>{setMembers(next);localStorage.setItem(key,JSON.stringify(next))};
 const counts=useMemo(()=>({active:members.filter(m=>m.status==='active').length,invited:members.filter(m=>m.status==='invited').length}),[members]);
 const invite=()=>{if(!email.trim())return;save([...members,{id:crypto.randomUUID(),email:email.trim().toLowerCase(),name:name.trim()||email.split('@')[0],role,status:'invited'}]);setEmail('');setName('')};
 return <div className="v20-team-page"><section className="v20-team-hero"><div><span><ShieldCheck/>Phân quyền quản trị</span><h2>Nhân sự và quyền truy cập</h2><p>Thiết lập vai trò theo đúng phạm vi công việc. Quyền được áp dụng cho menu, route và hành động quản trị.</p></div><div className="v20-team-metrics"><article><b>{counts.active}</b><span>Đang hoạt động</span></article><article><b>{counts.invited}</b><span>Đang chờ</span></article></div></section>
 <div className="v20-team-grid"><section className="v20-team-card"><header><div><UserPlus/><span><b>Mời thành viên</b><small>Thêm email và chọn vai trò phù hợp.</small></span></div></header><div className="v20-team-form"><label>Họ tên<input value={name} onChange={e=>setName(e.target.value)} placeholder="Nguyễn Văn A"/></label><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@domain.com"/></label><label>Vai trò<select value={role} onChange={e=>setRole(e.target.value as AdminRole)}>{Object.entries(roleLabels).filter(([r])=>r!=='owner').map(([r,l])=><option key={r} value={r}>{l}</option>)}</select></label><Button onClick={invite}><UserPlus/>Gửi lời mời</Button></div></section>
 <section className="v20-team-card is-wide"><header><div><UsersRound/><span><b>Thành viên</b><small>Quản lý vai trò và trạng thái truy cập.</small></span></div></header><div className="v20-member-list">{members.map(member=><article key={member.id}><span className="v20-member-avatar">{member.name.slice(0,1).toUpperCase()}</span><div><b>{member.name}</b><small>{member.email}</small></div><select value={member.role} disabled={member.role==='owner'} onChange={e=>save(members.map(m=>m.id===member.id?{...m,role:e.target.value as AdminRole}:m))}>{Object.entries(roleLabels).map(([r,l])=><option key={r} value={r}>{l}</option>)}</select><span className={`v20-status ${member.status}`}>{member.status==='active'?<Check/>:<LockKeyhole/>}{member.status==='active'?'Hoạt động':'Đã mời'}</span></article>)}</div></section></div>
 <section className="v20-permission-matrix"><header><h3>Ma trận quyền</h3><p>Quyền mặc định theo từng vai trò.</p></header><div className="v20-role-cards">{(Object.keys(roleLabels) as AdminRole[]).map(r=><article key={r}><h4>{roleLabels[r]}</h4><ul>{rolePermissions[r].map(p=><li key={p}><Check/>{p.replaceAll('.',' · ')}</li>)}</ul></article>)}</div></section></div>}
