import{useMemo,useState,type ReactNode}from'react';
import{Link,useOutletContext}from'react-router-dom';
import{ArrowRight,ChevronDown,Clock3,Heart,Minus,Plus,ShieldCheck,ShoppingBag,Truck,X,ZoomIn}from'lucide-react';
import{useCartActions,useCommerce}from'./context';
import type{Collection,Product,Section,TemplateKey,Theme,ThemeBlock}from'./types';
import{discount,money}from'./utils';
import{resolvesCollectionProducts}from'./collection-utils';
export function ProductCard({p,compact=false}:{p:Product;compact?:boolean}){const{addToCart}=useCartActions(),off=discount(p.price,p.compareAtPrice);return <article className={`product-card ${compact?'compact':''}`}><div className="product-media"><Link to={`/products/${p.handle}`}><img src={p.images[0]} alt={p.title}/></Link>{off>0&&<span>-{off}%</span>}<button className="wish" aria-label="Yêu thích"><Heart/></button><button className="quick" onClick={()=>addToCart(p.id,p.variants[0]?.id||'',1)}><ShoppingBag/>Thêm nhanh</button></div><div className="product-meta"><small>{p.vendor}</small><Link to={`/products/${p.handle}`}>{p.title}</Link><div><b>{money(p.price)}</b>{p.compareAtPrice>p.price&&<del>{money(p.compareAtPrice)}</del>}</div></div></article>}
const flattenBlocks=(items:ThemeBlock[]):ThemeBlock[]=>items.flatMap(item=>item.type==='group'?(item.visible?flattenBlocks(item.children||[]):[]):item.visible?[item]:[]);
const block=(items:ThemeBlock[],type:ThemeBlock['type'])=>flattenBlocks(items).find(x=>x.type===type);
const blocks=(items:ThemeBlock[],type:ThemeBlock['type'])=>flattenBlocks(items).filter(x=>x.type===type);
function Heading({eyebrow,title,link='/collections'}:{eyebrow?:string;title:string;link?:string}){return <div className="heading"><div>{eyebrow&&<small>{eyebrow}</small>}<h2>{title}</h2></div><Link to={link}>Xem tất cả<ArrowRight/></Link></div>}
function HomeSection({section}:{section:Section}){const{collections,products}=useCommerce();if(section.type==='hero'){const h=block(section.blocks,'heading'),text=block(section.blocks,'text'),button=block(section.blocks,'button');return <section className={`hero align-${section.settings.alignment||'left'}`} style={{minHeight:Number(section.settings.height||680)}}><img src={String(section.settings.image||'')} alt="TimeForge"/><div className="shade" style={{opacity:Number(section.settings.overlay||42)/100}}/><div className="hero-copy"><small>{String(h?.settings.eyebrow||'')}</small><h1>{String(h?.settings.text||'')}</h1><p>{String(text?.settings.text||'')}</p>{button&&<Link to={String(button.settings.link||'/collections')}>{String(button.settings.label||'Khám phá')}<ArrowRight/></Link>}</div></section>}
if(section.type==='trust')return <section className="trust">{blocks(section.blocks,'iconText').map(x=><div key={x.id}>{String(x.settings.icon)==='truck'?<Truck/>:String(x.settings.icon)==='clock'?<Clock3/>:<ShieldCheck/>}<span><b>{String(x.settings.title)}</b>{String(x.settings.text)}</span></div>)}</section>;
if(section.type==='collections')return <section className="section"><Heading eyebrow="CURATED FOR YOU" title={String(section.settings.title||'Bộ sưu tập nổi bật')}/><div className={`collection-grid layout-${section.settings.layout||'cards'}`}>{collections.filter(c=>c.status==='active').slice(0,Number(section.settings.limit||3)).map(c=><Link key={c.id} to={`/collections/${c.handle}`}><img src={c.image} alt={c.title}/><div><small>{c.description}</small><h3>{c.title}</h3><b>Khám phá<ArrowRight/></b></div></Link>)}</div></section>;
if(section.type==='products'){let source=products.filter(p=>p.status==='active'&&p.published);const handle=String(section.settings.collectionHandle||'');if(handle){const c=collections.find(x=>x.handle===handle);if(c)source=resolvesCollectionProducts(c,source)}return <section className="section"><Heading eyebrow="TIMEFORGE PICKS" title={String(section.settings.title||'Sản phẩm nổi bật')}/><div className={`product-grid columns-${section.settings.columns||4}`}>{source.slice(0,Number(section.settings.limit||8)).map(p=><ProductCard p={p} key={p.id}/>)}</div></section>}
if(section.type==='imageText'){const h=block(section.blocks,'heading'),text=block(section.blocks,'text'),button=block(section.blocks,'button');return <section className={`story image-${section.settings.imagePosition||'left'}`}><img src={String(section.settings.image||'')} alt="TimeForge"/><div><small>{String(h?.settings.eyebrow||'')}</small><h2>{String(h?.settings.text||'')}</h2><p>{String(text?.settings.text||'')}</p>{button&&<Link to={String(button.settings.link||'/pages/about')}>{String(button.settings.label||'Xem thêm')}<ArrowRight/></Link>}</div></section>}
if(section.type==='richText'){const h=block(section.blocks,'heading'),text=block(section.blocks,'text'),button=block(section.blocks,'button');return <section className={`rich-section align-${section.settings.alignment||'center'} width-${section.settings.width||'narrow'}`}><small>{String(h?.settings.eyebrow||'')}</small><h2>{String(h?.settings.text||'')}</h2><p>{String(text?.settings.text||'')}</p>{button&&<Link to={String(button.settings.link||'/collections')}>{String(button.settings.label||'Xem thêm')}</Link>}</section>}
if(section.type==='newsletter'){const h=block(section.blocks,'heading'),text=block(section.blocks,'text');return <section className={`newsletter ${section.settings.background==='dark'?'dark':''}`}><div><small>{String(h?.settings.eyebrow||'')}</small><h2>{String(h?.settings.text||'')}</h2><p>{String(text?.settings.text||'')}</p></div><form onSubmit={e=>e.preventDefault()}><input placeholder="Địa chỉ email"/><button>Đăng ký</button></form></section>};return null}
export function HomeTemplate({theme}:{theme:Theme}){return <>{theme.templates.home.sections.filter(s=>s.visible).map(s=><HomeSection key={s.id} section={s}/>)}</>}
export function ProductMainSection({section,product}:{section:Section;product:Product}){
  const{addToCart}=useCartActions();
  let openCart=()=>{};
  try{openCart=useOutletContext<{openCart:()=>void}>().openCart}catch{}
  const images=product.images.length?product.images:['https://placehold.co/1200x1200/f3f1ec/777?text=TimeForge'];
  const[img,setImg]=useState(0),[q,setQ]=useState(1),[v,setV]=useState(product.variants[0]?.id||''),[acc,setAcc]=useState(()=>blocks(section.blocks,'accordion').find(x=>Boolean(x.settings.open))?.id||''),[zoom,setZoom]=useState(false),[wished,setWished]=useState(false);
  const selectedVariant=useMemo(()=>product.variants.find(x=>x.id===v)||product.variants[0],[product.variants,v]);
  const currentPrice=selectedVariant?.price??product.price,currentCompare=selectedVariant?.compareAtPrice??product.compareAtPrice,currentInventory=selectedVariant?.inventory??product.inventory;
  const info=block(section.blocks,'productInfo'),priceBlock=block(section.blocks,'price'),variantBlock=block(section.blocks,'variantPicker'),quantityBlock=block(section.blocks,'quantity'),buyBlock=block(section.blocks,'buyButtons');
  const buy=()=>{addToCart(product.id,v,q);openCart()};
  return <div className="product-page"><section className={`product-detail gallery-${section.settings.gallerySize||'medium'} thumbs-${section.settings.thumbnailPosition||'left'}`}>
    <div className="gallery" aria-label="Hình ảnh sản phẩm">
      <div className="thumbs" role="list">{images.map((x,i)=><button type="button" aria-label={`Xem ảnh ${i+1}`} className={i===img?'active':''} key={`${x}-${i}`} onClick={()=>setImg(i)}><img src={x} alt={`${product.title} ${i+1}`}/></button>)}</div>
      <div className="main-image">
        <button type="button" className="main-image-click" aria-label="Mở ảnh phóng to" onClick={()=>setZoom(true)}><img src={images[img]} alt={product.title}/></button>
        <button type="button" className="zoom-trigger" aria-label="Phóng to ảnh" onClick={()=>setZoom(true)}><ZoomIn/><span>Phóng to</span></button>
        {images.length>1&&<span className="image-counter">{img+1}/{images.length}</span>}
      </div>
    </div>
    <div className={`buybox ${section.settings.stickyInfo?'sticky':''}`}>
      {info&&<div className="product-title-block"><div className="product-kicker">{Boolean(info.settings.showVendor)&&product.vendor}</div><h1>{product.title}</h1>{Boolean(info.settings.showSku)&&<p className="sku-line">SKU: {selectedVariant?.sku||product.sku||'—'}</p>}</div>}
      {priceBlock&&<div className="price"><b>{money(currentPrice)}</b>{Boolean(priceBlock.settings.showCompare)&&currentCompare>currentPrice&&<del>{money(currentCompare)}</del>}{Boolean(priceBlock.settings.showDiscount)&&currentCompare>currentPrice&&<span>-{discount(currentPrice,currentCompare)}%</span>}</div>}
      {info&&Boolean(info.settings.showStock)&&<p className={`stock ${currentInventory>0?'in-stock':'out-stock'}`}><i/>{currentInventory>0?`Còn hàng · ${currentInventory} sản phẩm`:'Tạm hết hàng'}</p>}
      {variantBlock&&product.variants.length>1&&<div className="variants"><b>Phiên bản</b><div>{product.variants.map(x=><button type="button" className={v===x.id?'active':''} onClick={()=>setV(x.id)} key={x.id}>{x.title}</button>)}</div></div>}
      {quantityBlock&&<div className="purchase-panel"><div className="quantity-field"><span>Số lượng</span><div className="qty"><button type="button" aria-label="Giảm số lượng" onClick={()=>setQ(Math.max(1,q-1))}><Minus/></button><strong>{q}</strong><button type="button" aria-label="Tăng số lượng" onClick={()=>setQ(Math.min(Math.max(1,currentInventory||99),q+1))}><Plus/></button></div></div><div className="purchase-actions">{buyBlock&&<button type="button" className="add-cart" disabled={currentInventory<=0} onClick={buy}><ShoppingBag/><span>{currentInventory>0?'Thêm vào giỏ':'Tạm hết hàng'}</span></button>}{buyBlock&&Boolean(buyBlock.settings.showWishlist)&&<button type="button" className={`wishlist-button ${wished?'active':''}`} aria-label="Yêu thích" aria-pressed={wished} onClick={()=>setWished(x=>!x)}><Heart fill={wished?'currentColor':'none'}/></button>}</div></div>}
      {buyBlock&&Boolean(buyBlock.settings.showBuyNow)&&<button type="button" className="buy-now" disabled={currentInventory<=0} onClick={buy}>Mua ngay</button>}
      <div className="benefits"><div><Truck/><span><b>Giao hàng an toàn</b>Đóng gói kỹ trước khi gửi</span></div><div><ShieldCheck/><span><b>Bảo hành rõ ràng</b>Chính sách theo từng sản phẩm</span></div></div>
      <div className="product-accordions">{blocks(section.blocks,'accordion').map(a=>{const source=String(a.settings.source),content:ReactNode=source==='description'?<div dangerouslySetInnerHTML={{__html:product.descriptionHtml||`<p>${product.descriptionText}</p>`}}/>:source==='shipping'?<p>Giao hàng dự kiến 1–4 ngày. Hỗ trợ kiểm tra tình trạng đơn hàng.</p>:<p>Chính sách bảo hành và đổi trả được xác nhận theo từng sản phẩm.</p>;return <div className="accordion" key={a.id}><button type="button" onClick={()=>setAcc(acc===a.id?'':a.id)}><b>{String(a.settings.title)}</b><ChevronDown className={acc===a.id?'active':''}/></button>{acc===a.id&&<div>{content}</div>}</div>})}</div>
    </div>
  </section>{zoom&&<div className="product-zoom" role="dialog" aria-modal="true" aria-label="Ảnh sản phẩm phóng to"><button className="product-zoom-backdrop" aria-label="Đóng" onClick={()=>setZoom(false)}/><div className="product-zoom-stage"><button className="product-zoom-close" aria-label="Đóng" onClick={()=>setZoom(false)}><X/></button><img src={images[img]} alt={product.title}/><div className="product-zoom-thumbs">{images.map((x,i)=><button type="button" className={i===img?'active':''} onClick={()=>setImg(i)} key={`${x}-zoom-${i}`}><img src={x} alt=""/></button>)}</div></div></div>}</div>
}
export function ProductTemplate({theme,product}:{theme:Theme;product:Product}){const{products}=useCommerce();return <>{theme.templates.product.sections.filter(s=>s.visible).map(s=>s.type==='productMain'?<ProductMainSection key={s.id} section={s} product={product}/>:s.type==='trust'?<HomeSection key={s.id} section={s}/>:s.type==='productRecommendations'?<section className="section related" key={s.id}><Heading eyebrow="YOU MAY ALSO LIKE" title={String(s.settings.title||'Sản phẩm liên quan')}/><div className={`product-grid columns-${s.settings.columns||4}`}>{products.filter(x=>x.id!==product.id&&(x.vendor===product.vendor||x.productType===product.productType)).slice(0,Number(s.settings.limit||4)).map(x=><ProductCard key={x.id} p={x}/>)}</div></section>:<HomeSection key={s.id} section={s}/>)}</>}
export function CollectionTemplate({theme,collection,products,toolbar,sidebar}:{theme:Theme;collection?:Collection;products:Product[];toolbar:ReactNode;sidebar:ReactNode}){return <>{theme.templates.collection.sections.filter(s=>s.visible).map(s=>s.type==='collectionBanner'?<section className="collection-hero" key={s.id} style={{minHeight:Number(s.settings.height||360)}}><div><small>TIMEFORGE COLLECTION</small><h1>{collection?.title||'Tất cả đồng hồ'}</h1><p>{collection?.description||'Khám phá những thiết kế được TimeForge tuyển chọn.'}</p></div>{Boolean(s.settings.showImage)&&collection?.image&&<img src={collection.image} alt=""/>}</section>:s.type==='collectionGrid'?<div key={s.id}>{toolbar}<div className="collection-layout">{sidebar}<div className={`product-grid collection-products columns-${s.settings.columns||4}`}>{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></div></div>:<HomeSection key={s.id} section={s}/>)}</>}
export function ThemeSectionCanvas({theme,template,section}:{theme:Theme;template:TemplateKey;section:Section}){const{products,collections}=useCommerce();const sample=products[0];if(template==='home')return <HomeSection section={section}/>;if(template==='product'&&sample){if(section.type==='productMain')return <ProductMainSection section={section} product={sample}/>;if(section.type==='trust')return <HomeSection section={section}/>;if(section.type==='productRecommendations')return <section className="section related"><Heading eyebrow="GỢI Ý PHÙ HỢP" title={String(section.settings.title||'Sản phẩm liên quan')}/><div className={`product-grid columns-${section.settings.columns||4}`}>{products.filter(x=>x.id!==sample.id).slice(0,Number(section.settings.limit||4)).map(x=><ProductCard key={x.id} p={x}/>)}</div></section>;return <HomeSection section={section}/>};if(template==='collection'){if(section.type==='collectionBanner')return <section className="collection-hero" style={{minHeight:Number(section.settings.height||360)}}><div><small>TIMEFORGE COLLECTION</small><h1>{collections[0]?.title||'Tất cả đồng hồ'}</h1><p>{collections[0]?.description||'Khám phá những thiết kế được TimeForge tuyển chọn.'}</p></div>{Boolean(section.settings.showImage)&&collections[0]?.image&&<img src={collections[0].image} alt=""/>}</section>;if(section.type==='collectionGrid')return <div><div className="collection-toolbar"><button>Bộ lọc</button><span>{Math.min(products.length,8)} sản phẩm</span><select><option>Nổi bật</option></select></div><div className="collection-layout"><aside className="filters"><h3>Thương hiệu</h3><label><input type="checkbox"/> Versace</label></aside><div className={`product-grid collection-products columns-${section.settings.columns||4}`}>{products.slice(0,8).map(p=><ProductCard key={p.id} p={p}/>)}</div></div></div>;return <HomeSection section={section}/>};if(template==='search')return section.type==='searchResults'?<section className="search-head"><small>TÌM KIẾM TIMEFORGE</small><h1>Tìm sản phẩm</h1><form><input placeholder="Tên, thương hiệu hoặc SKU"/><button>Tìm kiếm</button></form></section>:<HomeSection section={section}/>;if(template==='cart')return section.type==='cartMain'?<div className="cart-page"><small>GIỎ HÀNG</small><h1>Giỏ hàng</h1><div className="cart-empty-page"><h2>Chưa có sản phẩm</h2></div></div>:<HomeSection section={section}/>;return section.type==='pageContent'?<article className="content-page"><small>TIMEFORGE</small><h1>Về TimeForge</h1><b>Một cửa hàng đồng hồ được xây quanh sự minh bạch.</b><p>Nội dung trang sẽ hiển thị tại đây.</p></article>:<HomeSection section={section}/>}
export function ThemePreviewCanvas({theme,template}:{theme:Theme;template:TemplateKey}){const{products,collections}=useCommerce();const sample=products[0];return <div className="preview-live" style={{'--accent':theme.settings.accent,'--store-bg':theme.settings.background,'--store-surface':theme.settings.surface,'--store-text':theme.settings.text,'--radius':`${theme.settings.radius}px`} as React.CSSProperties}><div className="preview-live-head"><b>{theme.settings.logoText}</b><span>Đồng hồ　Bộ sưu tập　Về TimeForge</span><i>⌕　♡　▢</i></div>{template==='home'?<HomeTemplate theme={theme}/>:template==='product'&&sample?<ProductTemplate theme={theme} product={sample}/>:template==='collection'?<CollectionTemplate theme={theme} collection={collections[0]} products={products.slice(0,8)} toolbar={<div className="collection-toolbar"><button>Bộ lọc</button><span>8 sản phẩm</span><select><option>Nổi bật</option></select></div>} sidebar={<aside className="filters"><h3>Thương hiệu</h3><label><input type="checkbox"/> Versace</label></aside>}/>:template==='search'?<section className="search-head"><small>SEARCH TIMEFORGE</small><h1>Tìm sản phẩm</h1><form><input placeholder="Tên, thương hiệu hoặc SKU"/><button>Tìm kiếm</button></form></section>:template==='cart'?<div className="cart-page"><small>YOUR BAG</small><h1>Giỏ hàng</h1><div className="cart-empty-page"><h2>Chưa có sản phẩm</h2></div></div>:<article className="content-page"><small>TIMEFORGE</small><h1>Về TimeForge</h1><b>Một cửa hàng đồng hồ được xây quanh sự minh bạch.</b><p>Nội dung trang sẽ hiển thị tại đây.</p></article>}</div>}
