import crypto from 'node:crypto';
import {firebaseEntries,firebaseRead,firebaseWrite} from '../../server/firebase-rest.js';

const b64=value=>Buffer.from(value).toString('base64url');
const safe=(a,b)=>{const left=Buffer.from(String(a||''));const right=Buffer.from(String(b||''));return left.length===right.length&&crypto.timingSafeEqual(left,right)};
const sign=(value,secret)=>crypto.createHmac('sha256',secret).update(value).digest('base64url');
const normalizePhone=value=>{let digits=String(value||'').replace(/\D/g,'');if(digits.startsWith('84')&&digits.length>=10)digits=`0${digits.slice(2)}`;return digits};
const normalizeEmail=value=>String(value||'').trim().toLowerCase();
const memberAuthKey=(phone,secret)=>crypto.createHmac('sha256',secret).update(`member:${phone}`).digest('hex').slice(0,40);
const entityKey=(prefix,value,secret)=>crypto.createHmac('sha256',secret).update(`${prefix}:${value}`).digest('hex').slice(0,36);
const passwordHash=(password,salt)=>crypto.scryptSync(password,salt,64).toString('hex');
const sessionToken=(customerId,secret)=>{const data={customerId,issuedAt:Date.now(),expiresAt:Date.now()+Number(process.env.CUSTOMER_SESSION_MINUTES||120)*60000};const payload=b64(JSON.stringify(data));return{token:`${payload}.${sign(payload,secret)}`,expiresAt:data.expiresAt}};
const verifySession=(token,secret)=>{try{const[payload,signature]=String(token||'').split('.');if(!payload||!signature||!safe(signature,sign(payload,secret)))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));if(!data.customerId||Number(data.expiresAt)<=Date.now())return null;return data}catch{return null}};
const cleanCustomer=customer=>({id:String(customer.id||''),name:String(customer.name||''),email:String(customer.email||''),phone:String(customer.phone||''),ordersCount:Number(customer.ordersCount||0),totalSpent:Number(customer.totalSpent||0),tags:Array.isArray(customer.tags)?customer.tags:[],createdAt:String(customer.createdAt||new Date().toISOString()),birthDate:customer.birthDate?String(customer.birthDate):undefined,membership:customer.membership,addresses:Array.isArray(customer.addresses)?customer.addresses:[],notes:Array.isArray(customer.notes)?customer.notes:[],acceptsMarketing:Boolean(customer.acceptsMarketing)});
const memberSettings=raw=>{
  const defaults=[['member','Member',0,1,30],['silver','Silver',5000000,1.1,45],['gold','Gold',10000000,1.25,60],['platinum','Platinum',20000000,1.5,90]];
  const tiers=defaults.map((item,index)=>{const source=Array.isArray(raw?.tiers)?raw.tiers[index]||{}:{};return{id:item[0],label:String(source.label||item[1]),minSpend:index===0?0:Math.max(0,Number(source.minSpend)||item[2]),creditMultiplier:Math.max(1,Number(source.creditMultiplier)||item[3]),holdMinutes:Math.max(10,Math.min(180,Number(source.holdMinutes)||item[4]))}});
  return{enabled:raw?.enabled!==false,fomoEnabled:raw?.fomoEnabled!==false,lowStockThreshold:Math.max(1,Math.min(10,Number(raw?.lowStockThreshold)||3)),personalHoldEnabled:raw?.personalHoldEnabled!==false,opportunityEnabled:raw?.opportunityEnabled!==false,opportunityHours:Math.max(1,Math.min(168,Number(raw?.opportunityHours)||48)),opportunityCreditMultiplier:Math.max(1,Math.min(5,Number(raw?.opportunityCreditMultiplier)||2)),tiers};
};
const eligibleOrders=(orders,customer)=>orders.filter(([,order])=>{
  const phone=normalizePhone(order?.customerPhone),email=normalizeEmail(order?.customerEmail);
  const belongs=String(order?.customerId||'')===String(customer.id||'')||(phone&&phone===normalizePhone(customer.phone))||(email&&customer.email&&email===normalizeEmail(customer.email));
  return belongs&&order?.paymentStatus==='paid'&&order?.status!=='cancelled'&&order?.fulfillmentStatus!=='returned';
});
const tierFor=(settings,spend)=>settings.tiers.reduce((best,tier)=>spend>=tier.minSpend?tier:best,settings.tiers[0]);
async function readCustomerById(customerId){const raw=await firebaseRead('timeforge/customers');const found=firebaseEntries(raw).find(([,customer])=>String(customer?.id||'')===String(customerId));return found?{key:found[0],customer:found[1],raw}:null}
async function findCustomer(identifier){
  const raw=await firebaseRead('timeforge/customers');const phone=normalizePhone(identifier),email=normalizeEmail(identifier);
  const found=firebaseEntries(raw).find(([,customer])=>(phone&&normalizePhone(customer?.phone)===phone)||(email&&normalizeEmail(customer?.email)===email));
  return found?{key:found[0],customer:found[1],raw}:null;
}
async function readProduct(productId){const raw=await firebaseRead('timeforge/products');const found=firebaseEntries(raw).find(([,product])=>String(product?.id||'')===String(productId));return found?{key:found[0],product:found[1]}:null}
async function memberOrders(customer){const raw=await firebaseRead('timeforge/orders').catch(()=>({}));const phone=normalizePhone(customer.phone),email=normalizeEmail(customer.email);return firebaseEntries(raw).map(([,order])=>order).filter(order=>String(order?.customerId||'')===String(customer.id)||(phone&&normalizePhone(order?.customerPhone)===phone)||(email&&normalizeEmail(order?.customerEmail)===email)).sort((a,b)=>String(b?.createdAt||'').localeCompare(String(a?.createdAt||'')))}
async function memberData(req,res,secret){const session=verifySession(req.body?.token,secret);if(!session)return res.status(401).json({message:'Phiên Member đã hết hạn.'});const record=await readCustomerById(session.customerId);if(!record||record.customer?.membership?.status!=='active')return res.status(403).json({message:'Tài khoản Member chưa hoạt động.'});const raw=await firebaseRead('timeforge/orders').catch(()=>({}));const entries=firebaseEntries(raw);const phone=normalizePhone(record.customer.phone),email=normalizeEmail(record.customer.email);const orders=entries.map(([,order])=>order).filter(order=>String(order?.customerId||'')===String(record.customer.id)||(phone&&normalizePhone(order?.customerPhone)===phone)||(email&&normalizeEmail(order?.customerEmail)===email)).sort((a,b)=>String(b?.createdAt||'').localeCompare(String(a?.createdAt||'')));const referrals=entries.map(([,order])=>order).filter(order=>String(order?.referralReferrerId||'')===String(record.customer.id));return res.status(200).json({customer:cleanCustomer(record.customer),orders,referrals})}
async function activeHolds(productId,variantId=''){const raw=await firebaseRead('timeforge/memberHolds').catch(()=>({}));const now=Date.now();return firebaseEntries(raw).map(([key,hold])=>({key,...hold})).filter(hold=>hold.productId===productId&&(!variantId||!hold.variantId||hold.variantId===variantId)&&Number(hold.expiresAt)>now&&hold.status==='active')}

async function registerMember(req,res,secret){
  const name=String(req.body?.name||'').trim().replace(/\s+/g,' ');const phone=normalizePhone(req.body?.phone);const email=normalizeEmail(req.body?.email);const password=String(req.body?.password||'');const birthDate=String(req.body?.birthDate||'');const claimOrderCode=String(req.body?.claimOrderCode||'').trim().toLowerCase().replace(/\s/g,'');
  if(!req.body?.termsAccepted)return res.status(400).json({message:'Cần đồng ý điều khoản thành viên.'});
  if(name.length<2)return res.status(400).json({message:'Vui lòng nhập họ tên.'});
  if(!/^0\d{9,10}$/.test(phone))return res.status(400).json({message:'Số điện thoại chưa hợp lệ.'});
  if(password.length<8||password.length>72)return res.status(400).json({message:'Mật khẩu cần từ 8 đến 72 ký tự.'});
  if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({message:'Email chưa đúng định dạng.'});
  if(!/^\d{4}-\d{2}-\d{2}$/.test(birthDate)||new Date(`${birthDate}T00:00:00`).getTime()>Date.now())return res.status(400).json({message:'Ngày sinh chưa hợp lệ.'});
  const customersRaw=await firebaseRead('timeforge/customers').catch(()=>({}));const entries=firebaseEntries(customersRaw);const existing=entries.find(([,item])=>normalizePhone(item?.phone)===phone);const authKey=memberAuthKey(phone,secret);const authRecord=await firebaseRead(`timeforge/memberAuth/${authKey}`).catch(()=>null);
  if(authRecord)return res.status(409).json({message:'Số điện thoại này đã có tài khoản Member. Hãy đăng nhập.'});
  const ordersRaw=await firebaseRead('timeforge/orders').catch(()=>({}));const priorOrders=firebaseEntries(ordersRaw).filter(([,order])=>normalizePhone(order?.customerPhone)===phone).sort((a,b)=>String(b[1]?.createdAt||'').localeCompare(String(a[1]?.createdAt||'')));
  if(existing&&priorOrders.length){const expected=String(priorOrders[0][1]?.number||'').toLowerCase().replace(/\s/g,'');if(!claimOrderCode)return res.status(409).json({code:'CLAIM_REQUIRED',message:'SĐT này đã có đơn cũ. Nhập mã đơn gần nhất để liên kết lịch sử mua.'});if(claimOrderCode.length<4||!(claimOrderCode===expected||expected.endsWith(claimOrderCode)))return res.status(401).json({code:'CLAIM_INVALID',message:'Mã đơn gần nhất chưa đúng.'});}
  const now=new Date().toISOString();let key,customer;
  if(existing){key=existing[0];const old=existing[1];customer={...old,name,email:email||String(old.email||''),phone,birthDate:old.birthDate||birthDate,membership:{status:'active',joinedAt:old.membership?.joinedAt||now,source:'self_register'},tags:Array.from(new Set([...(Array.isArray(old.tags)?old.tags:[]),'Member']))};}
  else{key=`customer_${crypto.randomUUID().replaceAll('-','')}`;customer={id:key,name,email,phone,ordersCount:0,totalSpent:0,tags:['Member'],createdAt:now,birthDate,membership:{status:'active',joinedAt:now,source:'self_register'},addresses:[],notes:[],acceptsMarketing:false};}
  const salt=crypto.randomBytes(16).toString('hex');await firebaseWrite(`timeforge/customers/${key}`,customer);await firebaseWrite(`timeforge/memberAuth/${authKey}`,{customerId:customer.id,phoneHash:authKey,passwordHash:passwordHash(password,salt),salt,createdAt:now,updatedAt:now});
  const session=sessionToken(customer.id,secret);const linkedOrders=await memberOrders(customer);return res.status(201).json({customer:cleanCustomer(customer),orders:linkedOrders,...session});
}
async function passwordLogin(req,res,secret){
  const phone=normalizePhone(req.body?.phone);const password=String(req.body?.password||'');if(!phone||!password)return res.status(400).json({message:'Nhập số điện thoại và mật khẩu.'});const authKey=memberAuthKey(phone,secret);const auth=await firebaseRead(`timeforge/memberAuth/${authKey}`).catch(()=>null);if(!auth||!auth.salt||!auth.passwordHash)return res.status(401).json({message:'SĐT hoặc mật khẩu không đúng.'});const computed=passwordHash(password,auth.salt);if(!safe(computed,auth.passwordHash))return res.status(401).json({message:'SĐT hoặc mật khẩu không đúng.'});const found=await readCustomerById(auth.customerId);if(!found||found.customer?.membership?.status!=='active')return res.status(403).json({message:'Tài khoản Member chưa hoạt động.'});const session=sessionToken(found.customer.id,secret);const linkedOrders=await memberOrders(found.customer);return res.status(200).json({customer:cleanCustomer(found.customer),orders:linkedOrders,...session});
}
async function fomoStatus(req,res,secret){
  const productId=String(req.body?.productId||'');const variantId=String(req.body?.variantId||'');if(!productId)return res.status(400).json({message:'Missing product'});const found=await readProduct(productId);if(!found)return res.status(404).json({message:'Sản phẩm không tồn tại.'});const settings=memberSettings(await firebaseRead('timeforge/settings/member').catch(()=>({})));const holds=await activeHolds(productId,variantId);let customer=null,tier=null,eligibleSpend=0,nextTier=null,opportunity=null,selfHold=null;
  const session=verifySession(req.body?.token,secret);
  if(session){const record=await readCustomerById(session.customerId);if(record?.customer?.membership?.status==='active'){customer=record.customer;selfHold=holds.find(hold=>hold.customerId===customer.id)||null;const orders=firebaseEntries(await firebaseRead('timeforge/orders').catch(()=>({})));eligibleSpend=eligibleOrders(orders,customer).reduce((sum,[,order])=>sum+Math.max(0,Number(order.total)||0),0);tier=tierFor(settings,eligibleSpend);nextTier=settings.tiers[settings.tiers.findIndex(item=>item.id===tier.id)+1]||null;
      const opportunityKey=entityKey('opportunity',`${customer.id}:${productId}`,secret);opportunity=await firebaseRead(`timeforge/memberOpportunities/${opportunityKey}`).catch(()=>null);
      if(req.body?.saved===true&&settings.fomoEnabled&&settings.opportunityEnabled&&!opportunity){const now=Date.now();opportunity={id:opportunityKey,customerId:customer.id,productId,status:'active',creditMultiplier:settings.opportunityCreditMultiplier,createdAt:new Date(now).toISOString(),expiresAt:now+settings.opportunityHours*3600000};await firebaseWrite(`timeforge/memberOpportunities/${opportunityKey}`,opportunity);}
    }}
  const activeOpportunity=opportunity&&opportunity.status==='active'&&Number(opportunity.expiresAt)>Date.now()?opportunity:null;const holdsByOthers=customer?holds.filter(hold=>hold.customerId!==customer.id):holds;const selectedVariant=Array.isArray(found.product.variants)?found.product.variants.find(item=>String(item?.id||'')===variantId):null;const inventory=Math.max(0,Number(selectedVariant?.inventory??found.product.inventory)||0);return res.status(200).json({inventory,activeHolds:holds.length,availableInventory:Math.max(0,inventory-holdsByOthers.length),lowStock:inventory>0&&inventory<=settings.lowStockThreshold,selfHold,member:customer?{customerId:customer.id,tier,eligibleSpend,nextTier,remaining:nextTier?Math.max(0,nextTier.minSpend-eligibleSpend):0}:null,opportunity:activeOpportunity,settings:{fomoEnabled:settings.fomoEnabled,personalHoldEnabled:settings.personalHoldEnabled,lowStockThreshold:settings.lowStockThreshold}});
}
async function createHold(req,res,secret){
  const session=verifySession(req.body?.token,secret);if(!session)return res.status(401).json({message:'Phiên Member đã hết hạn. Đăng nhập lại để giữ hàng.'});const record=await readCustomerById(session.customerId);if(!record||record.customer?.membership?.status!=='active')return res.status(403).json({message:'Chỉ Member đang hoạt động mới được giữ hàng.'});const productId=String(req.body?.productId||'');const variantId=String(req.body?.variantId||'');const found=await readProduct(productId);if(!found)return res.status(404).json({message:'Sản phẩm không tồn tại.'});const settings=memberSettings(await firebaseRead('timeforge/settings/member').catch(()=>({})));if(!settings.fomoEnabled||!settings.personalHoldEnabled)return res.status(409).json({message:'Tính năng giữ hàng đang tạm tắt.'});const holds=await activeHolds(productId,variantId);const existing=holds.find(hold=>hold.customerId===record.customer.id);if(existing)return res.status(200).json({hold:existing});const selectedVariant=Array.isArray(found.product.variants)?found.product.variants.find(item=>String(item?.id||'')===variantId):null;const inventory=Math.max(0,Number(selectedVariant?.inventory??found.product.inventory)||0);if(holds.length>=inventory)return res.status(409).json({message:'Toàn bộ số lượng còn lại đang được giữ. Hãy thử lại sau.'});const orders=firebaseEntries(await firebaseRead('timeforge/orders').catch(()=>({})));const spend=eligibleOrders(orders,record.customer).reduce((sum,[,order])=>sum+Math.max(0,Number(order.total)||0),0);const tier=tierFor(settings,spend);const now=Date.now();const key=entityKey('hold',`${record.customer.id}:${productId}:${variantId||'default'}`,secret);const hold={id:key,customerId:record.customer.id,productId,variantId,status:'active',tierId:tier.id,createdAt:new Date(now).toISOString(),expiresAt:now+tier.holdMinutes*60000};await firebaseWrite(`timeforge/memberHolds/${key}`,hold);return res.status(201).json({hold});
}
async function releaseHold(req,res,secret){const session=verifySession(req.body?.token,secret);if(!session)return res.status(401).json({message:'Phiên Member đã hết hạn.'});const productId=String(req.body?.productId||'');const variantId=String(req.body?.variantId||'');const key=entityKey('hold',`${session.customerId}:${productId}:${variantId||'default'}`,secret);await firebaseWrite(`timeforge/memberHolds/${key}`,null);return res.status(200).json({ok:true});}

async function trackOrder(req,res){const number=String(req.body?.number||'').trim().toLowerCase();const identity=String(req.body?.identity||'').trim();if(!number||!identity)return res.status(400).json({message:'Nhập mã đơn và thông tin liên hệ.'});const phone=normalizePhone(identity),email=normalizeEmail(identity);const raw=await firebaseRead('timeforge/orders').catch(()=>({}));const found=firebaseEntries(raw).map(([,order])=>order).find(order=>String(order?.number||'').toLowerCase()===number&&((phone&&normalizePhone(order?.customerPhone)===phone)||(email&&normalizeEmail(order?.customerEmail)===email)));if(!found)return res.status(404).json({message:'Không tìm thấy đơn hàng phù hợp.'});return res.status(200).json({order:found})}

export default async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({message:'Method not allowed'});const action=String(req.body?.action||'otp');if(action==='track-order')try{return await trackOrder(req,res)}catch(error){return res.status(500).json({message:error instanceof Error?error.message:'Không thể tra cứu đơn.'})}const secret=process.env.CUSTOMER_SESSION_SECRET;if(!secret)return res.status(501).json({message:'Customer Member auth is not configured'});
  try{
    if(action==='register')return await registerMember(req,res,secret);
    if(action==='password-login')return await passwordLogin(req,res,secret);
    if(action==='member-data')return await memberData(req,res,secret);
    if(action==='fomo-status')return await fomoStatus(req,res,secret);
    if(action==='hold')return await createHold(req,res,secret);
    if(action==='release-hold')return await releaseHold(req,res,secret);
    const identifier=String(req.body?.identifier||'').trim();if(!identifier)return res.status(400).json({message:'Missing identifier'});const found=await findCustomer(identifier);const customer=found?.customer;if(!customer)return res.status(404).json({message:'Không tìm thấy hồ sơ khách hàng phù hợp.'});
    const code=String(Math.floor(100000+Math.random()*900000));const expiresAt=Date.now()+10*60*1000;const payload=b64(JSON.stringify({customerId:customer.id,identifier:identifier.toLowerCase(),codeHash:crypto.createHash('sha256').update(`${code}:${secret}`).digest('hex'),expiresAt}));const challenge=`${payload}.${sign(payload,secret)}`;
    const endpoint=process.env.CUSTOMER_OTP_DELIVERY_ENDPOINT;const apiKey=process.env.CUSTOMER_OTP_DELIVERY_API_KEY;if(endpoint){const delivery=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',...(apiKey?{'Authorization':`Bearer ${apiKey}`}:{})},body:JSON.stringify({identifier,code,expiresInMinutes:10,customerName:customer.name})});if(!delivery.ok)throw new Error(`OTP delivery failed (${delivery.status})`);}else if(process.env.CUSTOMER_OTP_DEV_MODE!=='true')return res.status(501).json({message:'OTP delivery provider is not configured'});
    return res.status(200).json({challenge,maskedIdentifier:identifier.includes('@')?identifier.replace(/(^.).*(@.*$)/,'$1***$2'):`***${identifier.slice(-4)}`,...(process.env.CUSTOMER_OTP_DEV_MODE==='true'?{devCode:code}:{})});
  }catch(error){return res.status(500).json({message:error instanceof Error?error.message:'Member request failed'});}
}
